# Generated by Django 3.1.2 on 2020-10-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_book_publishing_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,blank=True, null=True, related_name='book_ph', to='p_library.publishing_house', verbose_name='Publishing house'),
        ),
    ]
